name: Uso de secrets
on: [push]
jobs:
    print_secret:
        runs-on: ubuntu-latest
        steps:
            - name: Uso del secreto
              run: echo "El token secreto es ${{ secrets.TOKEN_DATABASE }}"