name: "Uso de variables"
on: [push]
env:
  variable_interna: "kasj923alajd83"
jobs:
  chequeo_variables:
    runs-on: ubuntu-latest
    steps:
      - name: Uso de variable interna
        run: echo "El token es $variable_interna"
      - name: Uso de variable externa
        run: echo "La API KEY es {{ vars.APIKEY }}"